# Generated by Django 3.2.9 on 2021-12-04 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_alter_fact_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='importance',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
