# Generated by Django 3.2.9 on 2021-12-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_alter_fact_importance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='text',
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.CharField(default='3 августа 2014', max_length=20),
            preserve_default=False,
        ),
    ]
